### ISSUE TITLE
[Bug]: 1.18, My Game Crashes when i place a Chocobo Nest

### ISSUE THREAD

**Issue by JustFlakeZ** [Mrbysco/ChocoCraft4#7]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

39.0.63

### Mod version

0.2.2

### Java version

Java 8 Update 321

### Issue Description

i played in my Survival World with my Custom Mod Pack and i wanted to place a Chocobo Nest to bread my Chocobos, but after i placed it down, my Game froze for some Seconds and then it crashed. The Texture for the Nest were also gone. 

### Additional Information

---- Minecraft Crash Report ----
// You're mean.

Time: 03.02.22, 22:24
Description: Exception ticking world

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.save(ChocoboNestBlockEntity.java:200) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.getUpdatePacket(ChocoboNestBlockEntity.java:215) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.m_183216_(ChocoboNestBlockEntity.java:40) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.save(ChocoboNestBlockEntity.java:200) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.getUpdatePacket(ChocoboNestBlockEntity.java:215) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.chococraft.common.blockentities.ChocoboNestBlockEntity.m_183216_(ChocoboNestBlockEntity.java:40) ~[chococraft-1.18.1-0.2.1.jar%2366!/:0.2.1] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['JustFlakeZ'/24613, l='ServerLevel[Bne und Leos supi dupi Weltr]', x=181.02, y=64.00, z=205.80]]
	Chunk stats: 14475
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,90,0), Section: (at 0,10,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 352878 game time, 600836 day time
	Level name: Bne und Leos supi dupi Weltr
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 32651 (now: false), thunder time: 22183 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 861152552 bytes (821 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8854
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 32659,75
	Virtual memory used (MB): 22389,23
	Swap memory total (MB): 24576,00
	Swap memory used (MB): 5034,13
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['JustFlakeZ'/24613, l='ServerLevel[Bne und Leos supi dupi Weltr]', x=181.02, y=64.00, z=205.80]]
	Data Packs: vanilla, mod:extraarmor (incompatible), mod:cyclopscore, mod:quarkoddities (incompatible), mod:dungeonsmod, mod:blue_skies (incompatible), mod:dusk (incompatible), mod:zombiehorsespawn, mod:shrines (incompatible), mod:jei (incompatible), mod:conjurer_illager (incompatible), mod:soaringstructures2 (incompatible), mod:doggytalents, mod:libraryferret, mod:goblintraders (incompatible), mod:waystones, mod:weaponthrow, mod:clumps (incompatible), mod:oresabovediamonds (incompatible), mod:awesomedungeon, mod:citadel, mod:sereneseasons (incompatible), mod:chromatocreeper, mod:stoneholm (incompatible), mod:dungeoncrawl, mod:snowundertrees, mod:chancecubes (incompatible), mod:balm (incompatible), mod:waterstrainer, mod:vtweaks (incompatible), mod:beyond_earth (incompatible), mod:paraglider (incompatible), mod:cloth_config (incompatible), mod:forge, mod:chococraft, mod:structure_gel, mod:ironchest, mod:dungeons_arise, mod:awesomedungeonocean, mod:farmersdelight, mod:repurposed_structures, mod:panthalassa (incompatible), mod:morevillagers (incompatible), mod:endrem (incompatible), mod:dungeons_enhanced, mod:majrusz_library (incompatible), mod:dimdungeons (incompatible), mod:flywheel, mod:create, mod:curios, mod:tetra, mod:patchouli, mod:mutil (incompatible), mod:collective, mod:advancednetherite, mod:autoreglib (incompatible), mod:quark (incompatible), mod:securitycraft, mod:villagertools (incompatible), mod:regrowth (incompatible), mod:gobber2 (incompatible), mod:majruszs_difficulty (incompatible), mod:majruszs_accessories (incompatible), mod:sapience, mod:cfm, mod:vampirism, mod:solcarrot (incompatible), mod:aquaculture (incompatible), mod:crossbowverhaul, mod:frostrealm (incompatible), mod:controllable, mod:chiselsandbits, mod:geckolib3 (incompatible), mod:ars_nouveau (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 27.20.100.8854
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		ExtraArmor-1.18-1.13.3.jar                        |Extra Armor                   |extraarmor                    |1.18-1.13.3         |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.18.1-1.13.0.jar                     |Cyclops Core                  |cyclopscore                   |1.13.0              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		DungeonsMod-1.18-1.4.60.jar                       |Dungeons Mod                  |dungeonsmod                   |1.18-1.4.60         |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.18.1-1.3.3.jar                       |Blue Skies                    |blue_skies                    |1.3.3               |DONE      |Manifest: NOSIGNATURE
		dusk-1.18-1.7.jar                                 |Dusk Mod                      |dusk                          |1.18-1.7            |DONE      |Manifest: NOSIGNATURE
		zombiehorsespawn_1.18.1-3.1.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |3.1                 |DONE      |Manifest: NOSIGNATURE
		Shrines-1.18.1-3.0.0-Beta9.jar                    |Shrines                       |shrines                       |1.18.1-3.0.0-Beta9  |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.18.1-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Soaring-Structures-2-1.18.1-2.1.jar               |Soaring Structures 2          |soaringstructures2            |1.18.1 - 2.1        |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.1-2.4.0.jar                     |Doggy Talents 2               |doggytalents                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.1-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.0-1.18.1.jar                    |Goblin Traders                |goblintraders                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |DONE      |Manifest: NOSIGNATURE
		WeaponThrow-1.18-5.5.jar                          |Weapon Throw                  |weaponthrow                   |1.18-5.5            |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		oresabovediamonds-1.18.1-v8.0.2.jar               |Ores Above Diamonds           |oresabovediamonds             |8.0.2               |DONE      |Manifest: NOSIGNATURE
		awesomedungeon-2.0.4.jar                          |Awesome Dungeon               |awesomedungeon                |2.0.4               |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |DONE      |Manifest: NOSIGNATURE
		chromatocreeper-1.18-1.1.jar                      |§3Chromato Creeper§r          |chromatocreeper               |1.1                 |DONE      |Manifest: NOSIGNATURE
		stoneholm-1.4.1.jar                               |Stoneholm                     |stoneholm                     |1.4.1               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.18.1-2.3.6.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.6               |DONE      |Manifest: NOSIGNATURE
		snowundertrees-1.18-1.1.5.jar                     |Snow Under Trees              |snowundertrees                |1.1.5               |DONE      |Manifest: NOSIGNATURE
		ChanceCubes-1.18.1-5.0.2.447.jar                  |Chance Cubes                  |chancecubes                   |1.18.1-5.0.2.447    |DONE      |Manifest: NOSIGNATURE
		balm-2.4.1+0 (1).jar                              |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		WaterStrainer-1.18-12.1.0.jar                     |Water Strainer                |waterstrainer                 |1.18-12.1.0         |DONE      |Manifest: NOSIGNATURE
		VTweaks-1.18-3.5.4.jar                            |V-Tweaks                      |vtweaks                       |3.5.4               |DONE      |Manifest: NOSIGNATURE
		Beyond-Earth-1.18.1-6.0b.jar                      |Beyond Earth                  |beyond_earth                  |6.0                 |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.18-1.5.0.0.jar                       |Paraglider                    |paraglider                    |1.5.0.0             |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.63-universal.jar                |Forge                         |forge                         |39.0.63             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		chococraft-1.18.1-0.2.1.jar                       |Chococraft 4                  |chococraft                    |0.2.1               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.1-2.1.2.jar                    |Structure Gel API             |structure_gel                 |2.1.2               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.18-13.0.7.jar                         |Iron Chests                   |ironchest                     |1.18-13.0.7         |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49c-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49c-1.18.1      |DONE      |Manifest: NOSIGNATURE
		AwesomeDungeonOcean-Forge-1.18-2.0.3.jar          |Awesome Dungeon Ocean         |awesomedungeonocean           |2.0.3               |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-4.2.3+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.2.3+1.18.1        |DONE      |Manifest: NOSIGNATURE
		panthalassa-0.8.0+1.18.1.jar                      |Panthalassa Mod               |panthalassa                   |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.18.1-3.1.1.jar              |More Villagers                |morevillagers                 |3.1.1               |DONE      |Manifest: NOSIGNATURE
		endrem_forge-5.0.1-R-1.18.1.jar                   |End Remastered                |endrem                        |5.0-R-1.18.1        |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.18.1-3.0-BETA.jar             |Dungeons Enhanced             |dungeons_enhanced             |3.0                 |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.18.1-2.7.1.jar                  |Majrusz Library               |majrusz_library               |2.7.1               |DONE      |Manifest: NOSIGNATURE
		dimdungeons-1.13.2-forge-1.18.1.jar               |Dimensional Dungeons          |dimdungeons                   |1.13.2              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.4.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.4.2      |DONE      |Manifest: NOSIGNATURE
		tetra-1.18.1-4.5.0.jar                            |Tetra                         |tetra                         |4.5.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-64 (1).jar                       |Patchouli                     |patchouli                     |1.18.1-64           |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.2.0.jar                            |mutil                         |mutil                         |4.2.0               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		advancednetherite-1.10.0-1.18.1.jar               |Advanced Netherite            |advancednetherite             |1.10.0              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		[1.18.1]+SecurityCraft+v1.9.0.2-beta1.jar         |SecurityCraft                 |securitycraft                 |1.9.0.2-beta1       |DONE      |Manifest: NOSIGNATURE
		villagertools-1.18-1.0.2.jar                      |villagertools                 |villagertools                 |1.18-1.0.2          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Regrowth--1.18.1-1.39.0.25.jar                    |Regrowth Mod                  |regrowth                      |1.18.1-1.39.0.25    |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.18.1-2.6.14.jar                   |Gobber 2                      |gobber2                       |2.6.14              |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.18.1-1.4.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.4.1               |DONE      |Manifest: NOSIGNATURE
		majruszsaccessories-1.18.1-0.4.1.jar              |Majrusz's Accessories         |majruszs_accessories          |0.4.1               |DONE      |Manifest: NOSIGNATURE
		sapience-1.18.1-1.0.2.jar                         |Sapience                      |sapience                      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre28-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre28         |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.18.1-1.8.0-beta.2.jar                 |Vampirism                     |vampirism                     |1.8.0-beta.2        |DONE      |Manifest: NOSIGNATURE
		SoL-Carrot-1.18.1-1.12.0.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.18.1-1.12.0       |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		crossbowverhaul-1.18.1-1.2.3-universal.jar        |Crossbowverhaul               |crossbowverhaul               |1.2.3               |DONE      |Manifest: NOSIGNATURE
		frostrealm-1.18.1-0.1.4.1.jar                     |FrostRealm                    |frostrealm                    |1.18.1-0.1.4.1      |DONE      |Manifest: NOSIGNATURE
		controllable-0.15.1-1.18.jar                      |Controllable                  |controllable                  |0.15.1              |DONE      |Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.1-1.2.77-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.77              |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.3.jar                     |GeckoLib                      |geckolib3                     |3.0.3               |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.1-2.1.1.jar                      |Ars Nouveau                   |ars_nouveau                   |2.1.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f1b8305f-b30f-410c-865b-95d0a4083d49
	FML: 39.0
	Forge: net.minecraftforge:39.0.63
	Flywheel Backend: GL33 Instanced Arrays

**Comment by Mrbysco** [comment]
Don't lie, you're using 0.2.1

**Comment by JustFlakeZ** [comment]
Oh damn, were the Bug already fixed in the newest Updates?

**Comment by Mrbysco** [comment]
This bug was fixed in 0.2.2 which you weren't using according to the crash log

**Comment by JustFlakeZ** [comment]
Darn, Next Time i should look more closely and maybe check the Mod if it got any Update. Well, thanks and have a nice Day
